apiVersion: v1
kind: Service
metadata:
  name: kourier
  namespace: kourier-system
  labels:
    networking.knative.dev/ingress-provider: kourier
spec:
  ports:
  - name: http2
    port: 80
    nodePort: 30881
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    nodePort: 30800
    protocol: TCP
    targetPort: 8443
  selector:
    app: 3scale-kourier-gateway
  type: NodePort

