apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: hikarifront
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: front-pod
        image: ultimatehikari/sberlab_07_21:front
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10


