apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/nfsshare"
