apiVersion: batch/v1
kind: Job
metadata:
  name: curl-pod
spec:
  template:
    spec:
      containers:
      - name: curl-pod
        image: ubuntu:focal
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
