apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/scaleDownDelay: "0s"
    spec:
      containerConcurrency: 1
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "NotKnative"
  traffic:
  - latestRevision: true
    percent: 90
  - revisionName: hello-00001
    percent: 10

