apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: pcmgc
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: front-pod
        image: ultimatehikari/pcmgc-front:0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        envFrom:
          - configMapRef:
               name: cm-front-env

