apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    app: pcmgc
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine:12
        ports:
          - containerPort: 2049
        securityContext:
          privileged: true
        env:
        - name: SHARED_DIRECTORY
          value: /nfsshare
        volumeMounts:
        - name: sharedir
          mountPath: "/nfsshare"
      volumes:
      - name: sharedir
        emptyDir: {}
