apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: pcmgc
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: api
  template:
    metadata:
      labels:
        tier: api
    spec:
      containers:
      - name: api-pod
        image: ultimatehikari/pcmgc-apiserver:0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
